### ISSUE TITLE
Update the AutoSuggest component with the fixed version of the script

### ISSUE THREAD

**Issue by ManuCiao** [vanWittlaer/VanWittlaerWhatThreeWords#1]
Hi @vanWittlaer 
Would you mind to update these lines to replace `4-latest` with this fixed version `4.1.6`

https://github.com/vanWittlaer/VanWittlaerWhat3Words/blob/cca8bd94bd84ed13e50d73e552cc53141e2782a6/src/Resources/views/storefront/component/analytics.html.twig#L13-L20

Also, could you remove the what3words key `?key={{ config('VanWittlaerWhatThreeWords.config.apiKey') }}` from this script? you can just pass it within the AutoSuggest component.  

it would be:

        <script
                type="module"
                src="https://cdn.what3words.com/javascript-components@4.1.6/dist/what3words/what3words.esm.js"
        />
        <script
                nomodule
                src="https://cdn.what3words.com/javascript-components@4.1.6/dist/what3words/what3words.js"
        />

**Comment by vanWittlaer** [comment]
Thx Manuela,

Please check v1.1.0 for the updated references and removed apikey.

Regards,
Benny

**Comment by ManuCiao** [comment]
Thanks for your update.
